<a href="https://colab.research.google.com/github/ranjanvrma/retail-sales-analytics/blob/main/notebooks/01_data_understanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
 df = pd.read_csv("/content/superstore_sales.csv")

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [5]:
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [6]:
df.shape

(9800, 18)

In [7]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.memory_usage()

Index              132
Row ID           78400
Order ID         78400
Order Date       78400
Ship Date        78400
Ship Mode        78400
Customer ID      78400
Customer Name    78400
Segment          78400
Country          78400
City             78400
State            78400
Postal Code      78400
Region           78400
Product ID       78400
Category         78400
Sub-Category     78400
Product Name     78400
Sales            78400
dtype: int64

# Questions

Set 1

In [10]:
# Which product categories generate the highest sales?

df.groupby('Category')['Sales'].sum().sort_values(ascending=False).head(1)

Category
Technology    827455.873
Name: Sales, dtype: float64

In [11]:
# Which sub-categories generate the highest sales?

df.groupby('Sub-Category')['Sales'].sum().sort_values(ascending=False).head(1)

Sub-Category
Phones    327782.448
Name: Sales, dtype: float64

In [12]:
# Which customer segment contributes the most sales?
df.groupby('Segment')['Sales'].sum().sort_values(ascending=False).head(1)

Segment
Consumer    1148060.531
Name: Sales, dtype: float64

In [13]:
# Which states generate the highest sales?
df.groupby('State')['Sales'].sum().sort_values(ascending=False).head(1)

State
California    446306.4635
Name: Sales, dtype: float64

In [14]:
# Which shipping mode is used the most?
df['Ship Mode'].value_counts().head(1)

Ship Mode
Standard Class    5859
Name: count, dtype: int64

Set 2

In [15]:
# Which Category generated the highest sales in each Region?
sales = df.groupby(['Region', 'Category'])['Sales'].sum()

sales.loc[sales.groupby(level=0).idxmax()]

Region   Category
Central  Technology    168739.208
East     Technology    263116.527
South    Technology    148195.208
West     Technology    247404.930
Name: Sales, dtype: float64

In [16]:
# Which State has the highest sales within each Category?
df.groupby(['Category', 'State'])['Sales'].sum()

Category    State
Furniture   Alabama         6332.4800
            Arizona        13525.2910
            Arkansas        3187.5500
            California    152216.5355
            Colorado       13220.2850
                             ...
Technology  Utah            2309.9040
            Vermont         1599.7600
            Virginia       24145.1600
            Washington     50536.7100
            Wisconsin       8376.3600
Name: Sales, Length: 142, dtype: float64

In [17]:
# Which Ship Mode is most commonly used by each Segment?
df.groupby(['Segment', 'Ship Mode']).size()

Segment      Ship Mode
Consumer     First Class        755
             Same Day           312
             Second Class      1003
             Standard Class    3031
Corporate    First Class        468
             Same Day           114
             Second Class       589
             Standard Class    1782
Home Office  First Class        278
             Same Day           112
             Second Class       310
             Standard Class    1046
dtype: int64

In [18]:
# Which Sub-Category sells the most in each State?
sales = df.groupby(['State', 'Sub-Category'])['Sales'].sum()

sales.loc[sales.groupby(level=0).idxmax()]

State                 Sub-Category
Alabama               Chairs           3915.540
Arizona               Phones           7388.776
Arkansas              Binders          2889.830
California            Phones          67139.680
Colorado              Chairs           8244.816
Connecticut           Chairs           2782.420
Delaware              Copiers         10499.970
District of Columbia  Machines         1379.920
Florida               Machines        24573.940
Georgia               Binders         11538.720
Idaho                 Tables           1824.810
Illinois              Phones          16771.784
Indiana               Copiers         18499.930
Iowa                  Chairs           1408.100
Kansas                Phones            756.690
Kentucky              Chairs           9233.570
Louisiana             Accessories      1667.800
Maine                 Phones            437.850
Maryland              Chairs           4329.910
Massachusetts         Storage          4288.780
Michigan              Binders         22821.970
Minnesota             Binders         12470.240
Mississippi           Tables           2516.060
Missouri              Copiers          5499.920
Montana               Copiers          2999.950
Nebraska              Phones           3045.800
Nevada                Binders          4897.184
New Hampshire         Accessories      2811.850
New Jersey            Machines         9899.850
New Mexico            Accessories      1163.800
New York              Phones          47001.800
North Carolina        Machines        12620.655
North Dakota          Storage           704.760
Ohio                  Phones          14405.448
Oklahoma              Phones           4550.980
Oregon                Phones           4451.336
Pennsylvania          Phones          19702.404
Rhode Island          Copiers          7399.870
South Carolina        Storage          2567.210
South Dakota          Appliances        416.320
Tennessee             Tables           6214.356
Texas                 Phones          28589.568
Utah                  Bookcases        2699.800
Vermont               Bookcases        4404.900
Virginia              Tables          14042.470
Washington            Tables          21668.640
West Virginia         Tables            673.344
Wisconsin             Chairs          11091.390
Wyoming               Chairs           1603.136
Name: Sales, dtype: float64

In [19]:
# Which Customer purchased the highest total sales?
df.groupby('Customer Name')['Sales'].sum().sort_values(ascending = False)

Customer Name
Sean Miller        25043.050
Tamara Chand       19052.218
Raymond Buch       15117.339
Tom Ashbrook       14595.620
Adrian Barton      14473.571
                     ...
Mitch Gastineau       16.739
Carl Jackson          16.520
Sung Chung            14.112
Lela Donovan           5.304
Thais Sissman          4.833
Name: Sales, Length: 793, dtype: float64

Set 3

In [20]:
# For each Category, show: Total Sales, Average Sales, Highest Sale, Lowest Sale
df.groupby('Category')['Sales'].agg(
    Total_Sales = 'sum',
    Average_Sales = 'mean',
    Highest_Sale = 'max',
    Lowest_Sale = 'min'
)

                 Total_Sales  Average_Sales  Highest_Sale  Lowest_Sale
Category
Furniture        728658.5757     350.653790      4416.174        1.892
Office Supplies  705422.3340     119.381001      9892.740        0.444
Technology       827455.8730     456.401474     22638.480        0.990

In [21]:
# For each Region, show: Total Sales, Average Sales, Number of Transactions
df.groupby('Region')['Sales'].agg(['sum', 'mean', 'count'])

                 sum        mean  count
Region
Central  492646.9132  216.357889   2277
East     669518.7260  240.401697   2785
South    389151.4590  243.524067   1598
West     710219.6845  226.184613   3140

In [22]:
# For each Customer Segment, show: Total Sales, Highest Sale, Lowest Sale, Average Sales
df.groupby('Segment')['Sales'].agg(['sum', 'max', 'min', 'mean'])

                      sum       max    min        mean
Segment
Consumer     1.148061e+06  13999.96  0.444  225.065777
Corporate    6.884941e+05  17499.95  0.556  233.150720
Home Office  4.249822e+05  22638.48  0.990  243.403309

In [23]:
# For each Ship Mode, show: Number of Orders, Total Sales, Average Sales
df.groupby('Ship Mode')['Sales'].agg(['count', 'sum', 'mean'])

                count           sum        mean
Ship Mode
First Class      1501  3.455723e+05  230.228020
Same Day          538  1.252190e+05  232.749143
Second Class     1902  4.499142e+05  236.547939
Standard Class   5859  1.340831e+06  228.849856

In [24]:
# For each State, show: Number of Customers, Total Sales
df.groupby('State')['Sales'].agg(['nunique', 'sum'])

                      nunique          sum
State
Alabama                    61   19510.6400
Arizona                   215   35272.6570
Arkansas                   58   11678.1300
California               1500  446306.4635
Colorado                  176   31841.5980
Connecticut                80   13384.3570
Delaware                   91   27322.9990
District of Columbia       10    2865.0200
Florida                   347   88436.5320
Georgia                   168   48219.1100
Idaho                      21    4382.4860
Illinois                  451   79236.5170
Indiana                   134   48718.4000
Iowa                       26    4443.5600
Kansas                     24    2914.3100
Kentucky                  135   36458.3900
Louisiana                  39    9131.0500
Maine                       8    1270.5300
Maryland                  104   23705.5230
Massachusetts             129   28634.4340
Michigan                  237   76136.0740
Minnesota                  86   29863.1500
Mississippi                53   10771.3400
Missouri                   64   22205.1500
Montana                    15    5589.3520
Nebraska                   38    7464.9300
Nevada                     39   16729.1020
New Hampshire              27    7292.5240
New Jersey                121   34610.9720
New Mexico                 37    4783.5220
New York                  938  306361.1470
North Carolina            234   55165.9640
North Dakota                7     919.9100
Ohio                      427   75130.3500
Oklahoma                   64   19683.3900
Oregon                    117   17284.4620
Pennsylvania              518  116276.6500
Rhode Island               53   22525.0260
South Carolina             40    8481.7100
South Dakota               12    1315.5600
Tennessee                 176   30661.8730
Texas                     838  168572.5322
Utah                       53   11220.0560
Vermont                    11    8929.3700
Virginia                  210   70636.7200
Washington                459  135206.8500
West Virginia               4    1209.8240
Wisconsin                 105   31173.4300
Wyoming                     1    1603.1360

Set 4

In [25]:
# Show all rows where: State == 'California'
df[df['State'] == 'California']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620
5,6,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860
6,7,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280
7,8,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152
8,9,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9745,9746,CA-2018-137505,24/11/2018,24/11/2018,Same Day,BP-11290,Beth Paige,Consumer,United States,Los Angeles,California,90008.0,West,FUR-TA-10000617,Furniture,Tables,Hon Practical Foundations 30 x 60 Training Tab...,364.080
9746,9747,CA-2018-137505,24/11/2018,24/11/2018,Same Day,BP-11290,Beth Paige,Consumer,United States,Los Angeles,California,90008.0,West,FUR-TA-10001676,Furniture,Tables,Hon 61000 Series Interactive Training Tables,71.088
9759,9760,CA-2017-146913,31/10/2017,05/11/2017,Standard Class,SF-20965,Sylvia Foulston,Corporate,United States,San Francisco,California,94109.0,West,FUR-CH-10001854,Furniture,Chairs,Office Star - Professional Matrix Back Chair w...,1403.920
9764,9765,CA-2015-123855,18/06/2015,23/06/2015,Standard Class,MC-18100,Mick Crebagga,Consumer,United States,Los Angeles,California,90036.0,West,TEC-PH-10000215,Technology,Phones,Plantronics Cordless Phone Headset with In-lin...,139.800
9768,9769,CA-2018-142328,07/12/2018,14/12/2018,Standard Class,TC-21535,Tracy Collins,Home Office,United States,San Francisco,California,94122.0,West,OFF-PA-10000380,Office Supplies,Paper,"REDIFORM Incoming/Outgoing Call Register, 11"" ...",50.040

In [26]:
# Show all rows where: Category == 'Technology'
df.query("Category == 'Technology'")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
7,8,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152
11,12,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.424
19,20,CA-2015-143336,27/08/2015,01/09/2015,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109.0,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480
26,27,CA-2017-121755,16/01/2017,20/01/2017,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,California,90049.0,West,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.570
35,36,CA-2017-117590,08/12/2017,10/12/2017,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9780,9781,CA-2017-153178,14/09/2017,18/09/2017,Standard Class,CL-12565,Clay Ludtke,Consumer,United States,Long Beach,New York,11561.0,East,TEC-PH-10001944,Technology,Phones,Wi-Ex zBoost YX540 Cellular Phone Signal Booster,437.850
9789,9790,CA-2018-144491,27/03/2018,01/04/2018,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,Central,TEC-AC-10004901,Technology,Accessories,Kensington SlimBlade Notebook Wireless Mouse w...,39.992
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

In [27]:
# Show all rows where: Sales > 1000
df[df['Sales'] > 1000]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
10,11,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184
24,25,CA-2016-106320,25/09/2016,30/09/2016,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,84057.0,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630
27,28,US-2016-150630,17/09/2016,21/09/2016,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430
35,36,CA-2017-117590,08/12/2017,10/12/2017,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544
54,55,CA-2017-105816,11/12/2017,17/12/2017,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,New York,10024.0,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9712,9713,CA-2015-114251,05/11/2015,10/11/2015,Standard Class,MD-17350,Maribeth Dona,Consumer,United States,Philadelphia,Pennsylvania,19143.0,East,OFF-ST-10003716,Office Supplies,Storage,Tennsco Double-Tier Lockers,1080.096
9741,9742,CA-2016-117086,08/11/2016,12/11/2016,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.900
9759,9760,CA-2017-146913,31/10/2017,05/11/2017,Standard Class,SF-20965,Sylvia Foulston,Corporate,United States,San Francisco,California,94109.0,West,FUR-CH-10001854,Furniture,Chairs,Office Star - Professional Matrix Back Chair w...,1403.920
9774,9775,CA-2015-169019,26/07/2015,30/07/2015,Standard Class,LF-17185,Luke Foster,Consumer,United States,San Antonio,Texas,78207.0,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,2177.584
9787,9788,CA-2018-144491,27/03/2018,01/04/2018,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,Central,FUR-BO-10001811,Furniture,Bookcases,"Atlantic Metals Mobile 5-Shelf Bookcases, Cust...",1023.332

In [28]:
# Show all Technology products with Sales greater than 1000.
df[(df['Category'] == 'Technology') & (df['Sales'] > 1000)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
35,36,CA-2017-117590,08/12/2017,10/12/2017,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544
54,55,CA-2017-105816,11/12/2017,17/12/2017,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,New York,10024.0,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950
165,166,CA-2015-139892,08/09/2015,12/09/2015,Standard Class,BM-11140,Becky Martin,Consumer,United States,San Antonio,Texas,78207.0,Central,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,8159.952
215,216,CA-2016-146262,02/01/2016,09/01/2016,Standard Class,VW-21775,Victoria Wilson,Corporate,United States,Medina,Ohio,44256.0,East,TEC-MA-10000864,Technology,Machines,Cisco 9971 IP Video Phone Charcoal,1188.000
251,252,CA-2017-145625,11/09/2017,17/09/2017,Standard Class,KC-16540,Kelly Collister,Consumer,United States,San Diego,California,92037.0,West,TEC-AC-10003832,Technology,Accessories,Logitech P710e Mobile Speakerphone,3347.370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9504,9505,CA-2017-113607,14/10/2017,18/10/2017,Standard Class,PW-19030,Pauline Webber,Corporate,United States,New York City,New York,10009.0,East,TEC-PH-10004094,Technology,Phones,Motorola L703CM,1091.930
9513,9514,CA-2017-125220,14/10/2017,19/10/2017,Standard Class,BE-11410,Bobby Elias,Consumer,United States,Appleton,Wisconsin,54915.0,Central,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,1649.750
9578,9579,CA-2018-152975,14/09/2018,16/09/2018,First Class,RB-19705,Roger Barcio,Home Office,United States,New York City,New York,10035.0,East,TEC-PH-10004586,Technology,Phones,Wilson SignalBoost 841262 DB PRO Amplifier Kit,1079.850
9660,9661,CA-2017-160717,06/06/2017,11/06/2017,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Santa Barbara,California,93101.0,West,TEC-PH-10001459,Technology,Phones,Samsung Galaxy Mega 6.3,3023.928
9673,9674,CA-2017-114867,23/12/2017,28/12/2017,Standard Class,FM-14290,Frank Merwin,Home Office,United States,Philadelphia,Pennsylvania,19143.0,East,TEC-PH-10002645,Technology,Phones,LG G2,1499.970

In [29]:
# Show all orders from: California, Technology and Sales > 1000
df.query("State == 'California' and Category == 'Technology' and Sales > 1000")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
251,252,CA-2017-145625,11/09/2017,17/09/2017,Standard Class,KC-16540,Kelly Collister,Consumer,United States,San Diego,California,92037.0,West,TEC-AC-10003832,Technology,Accessories,Logitech P710e Mobile Speakerphone,3347.370
406,407,CA-2018-117457,08/12/2018,12/12/2018,Standard Class,KH-16510,Keith Herrera,Consumer,United States,San Francisco,California,94110.0,West,TEC-CO-10004115,Technology,Copiers,Sharp AL-1530CS Digital Copier,1199.976
595,596,CA-2015-131450,08/08/2015,15/08/2015,Standard Class,LR-16915,Lena Radford,Consumer,United States,San Diego,California,92024.0,West,TEC-CO-10004115,Technology,Copiers,Sharp AL-1530CS Digital Copier,1199.976
753,754,CA-2017-110499,07/04/2017,09/04/2017,First Class,YC-21895,Yoseph Carroll,Corporate,United States,San Francisco,California,94110.0,West,TEC-CO-10002095,Technology,Copiers,Hewlett Packard 610 Color Digital Copier / Pri...,1199.976
814,815,CA-2018-143686,14/05/2018,14/05/2018,Same Day,PJ-19015,Pauline Johnson,Consumer,United States,Santa Ana,California,92704.0,West,TEC-AC-10001838,Technology,Accessories,Razer Tiamat Over Ear 7.1 Surround Sound PC Ga...,1399.930
1048,1049,CA-2015-139192,27/05/2015,01/06/2015,Second Class,LC-16885,Lena Creighton,Consumer,United States,San Francisco,California,94109.0,West,TEC-PH-10000486,Technology,Phones,Plantronics HL10 Handset Lifter,1113.504
1486,1487,CA-2016-140410,03/11/2016,07/11/2016,Standard Class,CM-12655,Corinna Mitchell,Home Office,United States,Los Angeles,California,90008.0,West,TEC-PH-10003580,Technology,Phones,Cisco IP Phone 7961G-GE VoIP phone,1212.848
1625,1626,CA-2016-157084,19/12/2016,24/12/2016,Standard Class,JG-15160,James Galang,Consumer,United States,Los Angeles,California,90049.0,West,TEC-AC-10002049,Technology,Accessories,Plantronics Savi W720 Multi-Device Wireless He...,1265.850
1805,1806,US-2017-116729,25/12/2017,28/12/2017,First Class,GK-14620,Grace Kelly,Corporate,United States,Los Angeles,California,90049.0,West,TEC-PH-10002200,Technology,Phones,Samsung Galaxy Note 2,2575.944
2113,2114,CA-2016-164882,31/10/2016,31/10/2016,Same Day,SG-20080,Sandra Glassco,Consumer,United States,Redlands,California,92374.0,West,TEC-PH-10001578,Technology,Phones,Polycom SoundStation2 EX Conference phone,1295.840
2220,2221,CA-2018-130841,28/07/2018,01/08/2018,Standard Class,MH-17620,Matt Hagelstein,Corporate,United States,San Francisco,California,94110.0,West,TEC-PH-10001817,Technology,Phones,Wilson Electronics DB Pro Signal Booster,1145.600
2273,2274,CA-2016-142944,06/03/2016,11/03/2016,Standard Class,JL-15850,John Lucas,Consumer,United States,San Francisco,California,94122.0,West,TEC-CO-10003763,Technology,Copiers,Canon PC1060 Personal Laser Copier,1119.984
2404,2405,CA-2018-108574,07/10/2018,11/10/2018,Standard Class,MG-18145,Mike Gockenbach,Consumer,United States,Los Angeles,California,90045.0,West,TEC-AC-10002049,Technology,Accessories,Logitech G19 Programmable Gaming Keyboard,1115.910
2709,2710,CA-2016-121797,30/01/2016,06/02/2016,Standard Class,CC-12145,Charles Crestani,Consumer,United States,Los Angeles,California,90049.0,West,TEC-MA-10000488,Technology,Machines,Bady BDG101FRU Card Printer,1919.976
2793,2794,CA-2015-154599,12/04/2015,17/04/2015,Standard Class,KN-16450,Kean Nguyen,Corporate,United States,Redondo Beach,California,90278.0,West,TEC-PH-10001557,Technology,Phones,Pyle PMP37LED,1075.088
3273,3274,CA-2018-133865,08/05/2018,12/05/2018,Standard Class,PS-19045,Penelope Sewall,Home Office,United States,Los Angeles,California,90032.0,West,TEC-CO-10001046,Technology,Copiers,Canon Imageclass D680 Copier / Fax,3359.952
3298,3299,CA-2018-136308,16/11/2018,16/11/2018,Same Day,MW-18235,Mitch Willingham,Corporate,United States,San Francisco,California,94122.0,West,TEC-MA-10000488,Technology,Machines,Bady BDG101FRU Card Printer,1919.976
3983,3984,CA-2017-135265,07/07/2017,09/07/2017,Second Class,CC-12370,Christopher Conant,Consumer,United States,Los Angeles,California,90045.0,West,TEC-CO-10003763,Technology,Copiers,Canon PC1060 Personal Laser Copier,2799.960
4218,4219,CA-2018-149881,01/04/2018,03/04/2018,First Class,NC-18535,Nick Crebassa,Corporate,United States,San Francisco,California,94110.0,West,TEC-MA-10000418,Technology,Machines,Cubify CubeX 3D Printer Double Head Print,4799.984
4619,4620,CA-2018-145219,24/12/2018,25/12/2018,First Class,RM-19675,Robert Marley,Home Office,United States,Los Angeles,California,90049.0,West,TEC-CO-10001449,Technology,Copiers,Hewlett Packard LaserJet 3310 Copier,2879.952
5425,5426,CA-2017-153598,03/12/2017,06/12/2017,First Class,NM-18520,Neoma Murray,Consumer,United States,Los Angeles,California,90045.0,West,TEC-AC-10003870,Technology,Accessories,Logitech Z-906 Speaker sys - home theater - 5....,1649.950
5812,5813,US-2016-163279,22/03/2016,26/03/2016,Standard Class,JD-16150,Justin Deggeller,Corporate,United States,San Diego,California,92037.0,West,TEC-PH-10001795,Technology,Phones,ClearOne CHATAttach 160 - speaker phone,1487.976
6010,6011,CA-2016-135580,30/12/2016,03/01/2017,Standard Class,CL-12565,Clay Ludtke,Consumer,United States,Los Angeles,California,90049.0,West,TEC-MA-10004002,Technology,Machines,Zebra GX420t Direct Thermal/Thermal Transfer P...,2548.560
6014,6015,CA-2017-159016,10/03/2017,11/03/2017,First Class,KF-16285,Karen Ferguson,Home Office,United States,Los Angeles,California,90008.0,West,TEC-PH-10002885,Technology,Phones,Apple iPhone 5,4158.912
6062,6063,CA-2016-111780,25/12/2016,30/12/2016,Second Class,RA-19285,Ralph Arnett,Consumer,United States,San Diego,California,92037.0,West,TEC-CO-10004202,Technology,Copiers,Brother DCP1000 Digital 3 in 1 Multifunction M...,1199.960
6575,6576,CA-2018-123085,03/03/2018,08/03/2018,Standard Class,EJ-13720,Ed Jacobs,Consumer,United States,Los Angeles,California,90008.0,West,TEC-AC-10000990,Technology,Accessories,Imation Bio 2GB USB Flash Drive Imation Corp,1049.440
6901,6902,US-2018-135013,24/07/2018,24/07/2018,Same Day,HR-14830,Harold Ryan,Corporate,United States,Huntington Beach,California,92646.0,West,TEC-CO-10001449,Technology,Copiers,Hewlett Packard LaserJet 3310 Copier,2399.960
7084,7085,CA-2018-118724,21/07/2018,25/07/2018,Second Class,AR-10825,Anthony Rawles,Corporate,United States,Concord,California,94521.0,West,TEC-PH-10002549,Technology,Phones,Polycom SoundPoint IP 450 VoIP phone,1626.192
7328,7329,US-2015-131275,18/03/2015,24/03/2015,Standard Class,SC-20050,Sample Company A,Home Office,United States,Burbank,California,91505.0,West,TEC-MA-10001148,Technology,Machines,Swingline SM12-08 MicroCut Jam Free Shredder,1279.968
7769,7770,CA-2017-155978,01/08/2017,01/08/2017,Same Day,TS-21205,Thomas Seio,Corporate,United States,Riverside,California,92503.0,West,TEC-PH-10002885,Technology,Phones,Apple iPhone 5,1039.728
8100,8101,CA-2017-169663,10/03/2017,13/03/2017,First Class,RH-19510,Rick Huthwaite,Home Office,United States,Los Angeles,California,90045.0,West,TEC-MA-10000984,Technology,Machines,Okidata MB760 Printer,3357.600
8102,8103,CA-2016-149846,22/05/2016,26/05/2016,Standard Class,SB-20185,Sarah Brown,Consumer,United States,Los Angeles,California,90045.0,West,TEC-MA-10004002,Technology,Machines,Zebra GX420t Direct Thermal/Thermal Transfer P...,2973.320
8301,8302,US-2018-167318,26/07/2018,01/08/2018,Standard Class,GZ-14545,George Zrebassa,Corporate,United States,Los Angeles,California,90036.0,West,TEC-AC-10003870,Technology,Accessories,Logitech Z-906 Speaker sys - home theater - 5....,1649.950
8451,8452,CA-2015-131387,28/04/2015,30/04/2015,First Class,AI-10855,Arianne Irving,Consumer,United States,San Francisco,California,94122.0,West,TEC-PH-10001459,Technology,Phones,Samsung Galaxy Mega 6.3,1679.960
8586,8587,CA-2018-162015,11/07/2018,18/07/2018,Standard Class,KB-16240,Karen Bern,Corporate,United States,Los Angeles,California,90049.0,West,TEC-AC-10003832,Technology,Accessories,Logitech P710e Mobile Speakerphone,1287.450
9165,9166,CA-2017-100300,24/06/2017,26/06/2017,Second Class,MJ-17740,Max Jones,Consumer,United States,San Diego,California,92037.0,West,TEC-MA-10000984,Technology,Machines,Okidata MB760 Printer,4476.800
9197,9198,CA-2015-103310,10/05/2015,15/05/2015,Standard Class,GM-14680,Greg Matthias,Consumer,United States,San Jose,California,95123.0,West,TEC-PH-10001817,Technology,Phones,Wilson Electronics DB Pro Signal Booster,1432.000
9234,9235,CA-2017-126732,02/09/2017,06/09/2017,Standard Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,California,90036.0,West,TEC-PH-10001530,Technology,Phones,Cisco Unified IP Phone 7945G VoIP phone,1091.168
9660,9661,CA-2017-160717,06/06/2017,11/06/2017,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Santa Barbara,California,93101.0,West,TEC-PH-10001459,Technology,Phones,Samsung Galaxy Mega 6.3,3023.928

Set 5

In [30]:
# Create a table where: Rows → Region, Values → Total Sales
table = df.pivot_table(index = 'Region', values = 'Sales', aggfunc= 'sum')
table

               Sales
Region
Central  492646.9132
East     669518.7260
South    389151.4590
West     710219.6845

In [31]:
# Create a table where: Rows → Category, Columns → Region, Values → Sales (sum)
table = df.pivot_table(index = 'Category', columns = 'Region', values = 'Sales', aggfunc = 'sum')
table

Region               Central        East       South         West
Category
Furniture        160317.4622  206461.388  116531.480  245348.2455
Office Supplies  163590.2430  199940.811  124424.771  217466.5090
Technology       168739.2080  263116.527  148195.208  247404.9300

In [32]:
# Rows: Segment, Columns: Ship Mode, Values: Sales (sum)
table = df.pivot_table(index = 'Segment', columns = 'Ship Mode', values = 'Sales', aggfunc = 'sum')
table

Ship Mode    First Class   Same Day  Second Class  Standard Class
Segment
Consumer     158104.9470  57452.273   230125.5356     702377.7754
Corporate    102580.0539  45121.323   139045.2908     401747.4071
Home Office   84887.2564  22645.443    80743.3530     236706.1245

In [33]:
# Rows: State, Values: Average Sales
table = df.pivot_table(index = 'State', values = 'Sales', aggfunc = 'mean')
table

                            Sales
State
Alabama                319.846557
Arizona                158.173350
Arkansas               194.635500
California             229.345562
Colorado               177.886022
Connecticut            163.223866
Delaware               293.795688
District of Columbia   286.502000
Florida                237.095260
Georgia                272.424350
Idaho                  208.689810
Illinois               164.050760
Indiana                360.877037
Iowa                   170.906154
Kansas                 121.429583
Kentucky               266.119635
Louisiana              222.708537
Maine                  158.816250
Maryland               225.766886
Massachusetts          212.106919
Michigan               300.933099
Minnesota              335.541011
Mississippi            203.232830
Missouri               336.441667
Montana                372.623467
Nebraska               196.445526
Nevada                 428.951333
New Hampshire          270.093481
New Jersey             283.696492
New Mexico             129.284378
New York               279.271784
North Carolina         223.343984
North Dakota           131.415714
Ohio                   165.485352
Oklahoma               298.233182
Oregon                 141.675918
Pennsylvania           199.788058
Rhode Island           409.545927
South Carolina         201.945476
South Dakota           109.630000
Tennessee              167.551219
Texas                  173.250290
Utah                   211.699170
Vermont                811.760909
Virginia               315.342500
Washington             268.267560
West Virginia          302.456000
Wisconsin              296.889810
Wyoming               1603.136000

In [34]:
# Rows: Category, Columns: Segment, Values: Sales (sum), Margins: Yes (Grand Total)
table = df.pivot_table(index = 'Category', columns = 'Segment', values = 'Sales', aggfunc = 'sum', margins = True)
table

Segment             Consumer    Corporate  Home Office           All
Category
Furniture         387696.258  220321.7018  120640.6159  7.286586e+05
Office Supplies   359352.608  224130.5360  121939.1900  7.054223e+05
Technology        401011.665  244041.8370  182402.3710  8.274559e+05
All              1148060.531  688494.0748  424982.1769  2.261537e+06